ARCHS = armv7 arm64 arm64e
LOCAL_INSTALL_PATH = /usr/lib/infobar/
include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = ibosversion

ibosversion_FILES = ibosversion.m
ibosversion_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/library.mk
