ARCHS = armv7 arm64 arm64e
LOCAL_INSTALL_PATH = /usr/lib/infobar/
include $(THEOS)/makefiles/common.mk

LIBRARY_NAME = ibname

ibname_FILES = ibname.m
ibname_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/library.mk
